name: CI/CD workflow

on:
  push:
    paths: hospital-management/api-gateway/**
      

jobs:
  pre-commit-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Checkout code
      uses: actions/checkout@v2

    - name: check gitleaks
      run: docker run --rm -v "$(pwd)":/path ${{ vars.DOCKER_HUB_REGISTRY }}/gitleaks:latest detect -v

    - name: license-finder
      run: |
          cd hospital-management/api-gateway
          docker run --rm -v "${pwd}":/scan ${{ vars.DOCKER_HUB_REGISTRY }}/license-finder:latest
      
    - name: OWASP Scan
      if: false
      run: |
         cd hospital-management/api-gateway
         mvn org.owasp:dependency-check-maven:check
 
    - name: Build code and create docker images
      run: |
        cd  hospital-management/api-gateway
        mvn clean install docker:build -Dimage.registry=${{ vars.DOCKER_HUB_REGISTRY }} -Dimage.tag=$GITHUB_REF_NAME

    - name: Log in to GitHub Docker Registry  
      uses: docker/login-action@v2
      with:
        username: ${{ vars.DOCKER_HUB_REGISTRY }}
        password: ${{ secrets.DOCKER_HUB_PAT }}

    - name: Docker push
      run: |
         CURRENT_FOLDER_NAME=$(basename $(pwd))
         docker push ${{ vars.DOCKER_HUB_REGISTRY }}/CURRENT_FOLDER_NAME:$GITHUB_REF_NAME
