name: CI/CD workflow

on:
  push:
    paths: hospital-management/appointment-service/**
       

jobs:
  pre-commit-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Checkout code
      uses: actions/checkout@v2

    - name: check gitleaks
      continue-on-error: true
      run: docker run --rm -v "$(pwd)":/path ${{ vars.DOCKER_HUB_REGISTRY }}/gitleaks:latest detect -v

    - name: Perform Google Formatter Check
      run: |
        cd hospital-management/appointment-service
        mvn com.spotify.fmt:fmt-maven-plugin:check
  

    - name: license-finder
      continue-on-error: true
      run: |
          cd hospital-management/appointment-service
          docker run --rm -v "$(pwd)":/scan ${{ vars.DOCKER_HUB_REGISTRY }}/license-finder:latest  
          

    - name: Check OSS scan
      run: |
        cd hospital-management/appointment-service
        mvn ossindex:audit

    - name: OWASP Scan
      if: false
      run: |
         cd hospital-management/appointment-service
         mvn org.owasp:dependency-check-maven:check
         
    - name: Build code and create docker images
      run: |
        cd hospital-management/appointment-service
        mvn clean install docker:build -Dimage.registry=${{ vars.DOCKER_HUB_REGISTRY }} -Dimage.tag=$GITHUB_REF_NAME

    - name: Log in to GitHub Docker Registry  
      uses: docker/login-action@v2
      with:
        username: ${{ vars.DOCKER_HUB_REGISTRY }}
        password: ${{ secrets.DOCKER_HUB_PAT }}

    - name: Docker push
      run: |
        cd hospital-management/appointment-service
        CURRENT_FOLDER_NAME=$(basename $(pwd))
        docker push ${{ vars.DOCKER_HUB_REGISTRY }}/$CURRENT_FOLDER_NAME:$GITHUB_REF_NAME
