name: base image build

on:
  push:
    paths:
       - dev-sec-ops/base-images/**

jobs:
    build-base-images:
      runs-on: ubuntu-latest

      steps:
        - name: checkout code
          uses: action/checkout@v4

        - name: build image
          run: docker build -t ${{vars.DOCKER_HUB_REGISTRY}}/license-finder:latest -f dev-sec-ops/base-images/license-finder.dockerfile .


        - name: log into docker registry
          uses: docker/login-action@v2
          with:
             username: ${{vars.DOCKER_HUB_REGISTRY}}  
             password: ${{secrets.DOCKER_HUB_PAT}}

        - name: docker push
          run: docker push  ${{vars.DOCKER_HUB_REGISTRY}}/license-finder:latest 
    
