name: CI/CD workflow

on:
  push:
    paths: hospital-management/**

jobs:
   pre-commit-scan:
      runs-on: ubuntu-latest
        

      steps:
         - name: setup java
           uses: actions/setup-java@v4
           with:
              distribution: 'temurin'
              java-version: '21'

         - name: checkout code
           uses: actions/checkout@v2
           
      
         - name: check git leaks
           continue-on-error: true
           run: |
               docker run --rm -v "$(pwd)":/path rameshwarshinde/gitleaks detect -v
                 
         - name: check oss scan
           run: |
                cd hospital-management/patient-service
                mvn ossindex:audit
              
         - name: build image
           run: |
                cd hospital-management/patient-service
                 mvn clean install docker:build
                 
              
            
          

             
                 

      
