name: CI/CD workflow

on:
  push:
    paths: hospital-management/directory-service/**
      

jobs:
  pre-commit-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check OSS scan
      run: |
        cd hospital-management/directory-service
        mvn ossindex:audit

    - name: Build code and create docker images
      run: |
       cd hospital-management/directory-service
       mvn clean install docker:build -Dimage.registry=${{ vars.DOCKER_HUB_REGISTRY }} -Dimage.tag=$GITHUB_REF_NAME

    - name: Log in to GitHub Docker Registry  
      uses: docker/login-action@v2
      with:
        username: ${{ vars.DOCKER_HUB_REGISTRY }}
        password: ${{ secrets.DOCKER_HUB_PAT }}

    - name: Docker push
      run: docker push ${{ vars.DOCKER_HUB_REGISTRY }}/directory-service:$GITHUB_REF_NAME
