name: CI/CD workflow for hospital-console

on:
  push:
    paths: hospital-management/hospital-console/**
       

jobs:
  clean-project:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Run maven clean
      run: |
        cd hospital-management/hospital-console
        mvn clean
